github: csteamengine
# patreon: your-patreon-username
# open_collective: your-collective-name
# ko_fi: your-kofi-username
# custom: ["https://buymeacoffee.com/yourname", "https://yourwebsite.com/donate"]
